/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    artists: Artist;
    plays: Play;
    productions: Production;
    events: Event;
    news: News;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    plays: PlaysSelect<false> | PlaysSelect<true>;
    productions: ProductionsSelect<false> | ProductionsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    homepage: Homepage;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment(s). Use "home" for the homepage.
   */
  slug: string;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline: string;
            subhead?: string | null;
            background?: ('marigold' | 'bolt' | 'leaf' | 'magenta' | 'paper') | null;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            headline: string;
            body?: string | null;
            color?: ('bolt' | 'leaf' | 'marigold' | 'magenta' | 'ink') | null;
            align?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'color';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            headline?: string | null;
            left: {
              heading: string;
              body?: string | null;
              image?: (number | null) | Media;
              href?: string | null;
            };
            right: {
              heading: string;
              body?: string | null;
              image?: (number | null) | Media;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoUp';
          }
        | {
            asset: number | Media;
            caption?: string | null;
            size?: ('inset' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            headline: string;
            body?: string | null;
            tone?: ('bolt' | 'leaf' | 'marigold' | 'magenta' | 'ink') | null;
            cta: {
              label: string;
              href: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            quote: string;
            attribution?: string | null;
            /**
             * e.g. publication or play title.
             */
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            kind: 'youtube' | 'vimeo' | 'iframe';
            /**
             * YouTube/Vimeo URL or any iframe-safe URL.
             */
            url: string;
            aspect?: ('16x9' | '4x3' | '1x1') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  slug: string;
  roles?: ('playwright' | 'director' | 'actor' | 'staff')[] | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  headshot?: (number | null) | Media;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plays".
 */
export interface Play {
  id: number;
  title: string;
  slug: string;
  playwright: number | Artist;
  synopsis?: string | null;
  themes?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  lifecycle: 'in_development' | 'produced' | 'published';
  media?:
    | {
        asset: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productions".
 */
export interface Production {
  id: number;
  title: string;
  slug: string;
  play: number | Play;
  /**
   * e.g. "2026 Festival"
   */
  season?: string | null;
  year?: number | null;
  venue?: string | null;
  director?: (number | null) | Artist;
  cast?: (number | Artist)[] | null;
  startsOn?: string | null;
  endsOn?: string | null;
  photos?:
    | {
        asset: number | Media;
        id?: string | null;
      }[]
    | null;
  program?: (number | null) | Media;
  ticketURL?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  type: 'reading' | 'workshop' | 'festival' | 'fundraiser' | 'other';
  startsAt: string;
  endsAt?: string | null;
  venue?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ticketURL?: string | null;
  hero?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  hero?: (number | null) | Media;
  publishedAt?: string | null;
  tags?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline: string;
            subhead?: string | null;
            background?: ('marigold' | 'bolt' | 'leaf' | 'magenta' | 'paper') | null;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            headline: string;
            body?: string | null;
            color?: ('bolt' | 'leaf' | 'marigold' | 'magenta' | 'ink') | null;
            align?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'color';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            headline?: string | null;
            left: {
              heading: string;
              body?: string | null;
              image?: (number | null) | Media;
              href?: string | null;
            };
            right: {
              heading: string;
              body?: string | null;
              image?: (number | null) | Media;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoUp';
          }
        | {
            asset: number | Media;
            caption?: string | null;
            size?: ('inset' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            headline: string;
            body?: string | null;
            tone?: ('bolt' | 'leaf' | 'marigold' | 'magenta' | 'ink') | null;
            cta: {
              label: string;
              href: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            quote: string;
            attribution?: string | null;
            /**
             * e.g. publication or play title.
             */
            source?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            kind: 'youtube' | 'vimeo' | 'iframe';
            /**
             * YouTube/Vimeo URL or any iframe-safe URL.
             */
            url: string;
            aspect?: ('16x9' | '4x3' | '1x1') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  source?: string | null;
  token: string;
  confirmedAt?: string | null;
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'plays';
        value: number | Play;
      } | null)
    | ({
        relationTo: 'productions';
        value: number | Production;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              background?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        color?:
          | T
          | {
              headline?: T;
              body?: T;
              color?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        twoUp?:
          | T
          | {
              headline?: T;
              left?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    image?: T;
                    href?: T;
                  };
              right?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    image?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              asset?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              headline?: T;
              body?: T;
              tone?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              kind?: T;
              url?: T;
              aspect?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  roles?: T;
  bio?: T;
  headshot?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plays_select".
 */
export interface PlaysSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  playwright?: T;
  synopsis?: T;
  themes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  lifecycle?: T;
  media?:
    | T
    | {
        asset?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productions_select".
 */
export interface ProductionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  play?: T;
  season?: T;
  year?: T;
  venue?: T;
  director?: T;
  cast?: T;
  startsOn?: T;
  endsOn?: T;
  photos?:
    | T
    | {
        asset?: T;
        id?: T;
      };
  program?: T;
  ticketURL?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  startsAt?: T;
  endsAt?: T;
  venue?: T;
  description?: T;
  ticketURL?: T;
  hero?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  hero?: T;
  publishedAt?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              background?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        color?:
          | T
          | {
              headline?: T;
              body?: T;
              color?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        twoUp?:
          | T
          | {
              headline?: T;
              left?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    image?: T;
                    href?: T;
                  };
              right?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    image?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              asset?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              headline?: T;
              body?: T;
              tone?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              source?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              kind?: T;
              url?: T;
              aspect?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  token?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  logoText?: string | null;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Small status bar above the nav (e.g. "Festival 2026 — May 24").
   */
  statusPills?:
    | {
        label: string;
        tone?: ('ink' | 'bolt' | 'leaf' | 'marigold' | 'magenta') | null;
        id?: string | null;
      }[]
    | null;
  whatsOn?:
    | {
        /**
         * e.g. "Now Playing", "Upcoming"
         */
        eyebrow?: string | null;
        title: string;
        body?: string | null;
        image?: (number | null) | Media;
        href: string;
        tone?: ('paper' | 'marigold' | 'leaf' | 'bolt' | 'magenta') | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'youtube' | 'tiktok';
        href: string;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    eyebrow?: string | null;
    headline: string;
    subhead?: string | null;
    /**
     * Looping background video (mp4 or webm). Muted, autoplay.
     */
    video?: (number | null) | Media;
    /**
     * Fallback image while video loads or if video missing.
     */
    poster?: (number | null) | Media;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  featuredPlay?: {
    eyebrow?: string | null;
    play?: (number | null) | Play;
    image?: (number | null) | Media;
  };
  /**
   * Full-bleed color block (e.g. festival announcement).
   */
  callout?: {
    eyebrow?: string | null;
    headline?: string | null;
    body?: string | null;
    tone?: ('bolt' | 'leaf' | 'marigold' | 'magenta' | 'ink') | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  logoText?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  statusPills?:
    | T
    | {
        label?: T;
        tone?: T;
        id?: T;
      };
  whatsOn?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        image?: T;
        href?: T;
        tone?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  tagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subhead?: T;
        video?: T;
        poster?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  featuredPlay?:
    | T
    | {
        eyebrow?: T;
        play?: T;
        image?: T;
      };
  callout?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        tone?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}